# Basics

In [3]:
import pandas as pd
import numpy as np
import timeit

In [2]:
df = pd.DataFrame({'Name':['RD','AG','Mimi'],'Class':[4,12,4]})
df

Class  Name
0      4    RD
1     12    AG
2      4  Mimi

In [3]:
df.rename(columns={'Name':'name','Class':'class'},inplace=True)
df

class  name
0      4    RD
1     12    AG
2      4  Mimi

In [4]:
list=[1,2,'ur',True]
list.append('e')
list
for i in range(1,4,2):
    print(list[i])

2
True


In [5]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [6]:
x='abd'
x1="india is world's best country"
x2='india is world\'s best country'
x3='''india is world's best country. Her reply was "so what can i do?".'''
print(x)
print(x1)
print(x2)
print(x3)

abd
india is world's best country
india is world's best country
india is world's best country. Her reply was "so what can i do?".


In [7]:
name = ' Ritz dey '
print(name.title())
print(name.upper())
print(name.lower())
print(name.lstrip())
print(name.rstrip())
print(name.strip())

 Ritz Dey 
 RITZ DEY 
 ritz dey 
Ritz dey 
 Ritz dey
Ritz dey


In [8]:
print(4*3)
print(4+3)
print(4/3)
print(4-3)
print('a'+'b')
print('a'*2)
#print('a'*'b')
#print('a'-'b')

12
7
1.3333333333333333
1
ab
aa


In [9]:
a=3
print(a)
print(type(a))
a='go to work'
print(a)
print(type(a))

3
<class 'int'>
go to work
<class 'str'>


In [10]:
a='3'
print(int(a))
print(float(a))
print(type(int(a)))
print(type(float(a)))
a=3
print(str(a))
print(type(str(a)))

3
3.0
<class 'int'>
<class 'float'>
3
<class 'str'>


In [62]:
x=bool(0)
print(x)
x=bool(0.0)
print(x)
x=bool(1)
print(x)
x=bool('')
print(x)
x=bool('a')
print(x)
print("True and True=",True and True)
print("True and False=",True and False)
print("False and False=",False and False)
print("True or True=",True or True)
print("True or False=",True or False)
print("False or False=",False or False)

False
False
True
False
True
True and True= True
True and False= False
False and False= False
True or True= True
True or False= True
False or False= False


In [12]:
# \t = tab \n = new line
print("Languages:\n\t1. Python\n\t2. C")

Languages:
	1. Python
	2. C


# List

In [63]:
l=[1,6,'abcd', True, ['A','B','C'],'A',9,10,11,{'A':1,'B':2}]
print(l[0])
print(l[1:3])
print(l[1:7:2])
print(l[:7:2])
print(l[::2])

print(l[-1])
print(l[-3:-1])

l[4:6]=[2,3]
print(l)

print([5]*4)

1
[6, 'abcd']
[6, True, 'A']
[1, 'abcd', ['A', 'B', 'C'], 9]
[1, 'abcd', ['A', 'B', 'C'], 9, 11]
{'A': 1, 'B': 2}
[10, 11]
[1, 6, 'abcd', True, 2, 3, 9, 10, 11, {'A': 1, 'B': 2}]


In [14]:
# changing one element
l[1]=6/2
print(l)
l[1]=int(6/2)
print(l)

# adding element in the end
l.append('Adding')
print(l)


# adding element in the middle
l.insert(1, 'in the middle')
print(l)
#delete by position
popped=l.pop(2)
print(l)
print(popped)

#delete by value
l.remove('in the middle')
print(l)

[1, 3.0, 'abcd', True, 2, 3, 9, 10, 11, {'A': 1, 'B': 2}]
[1, 3, 'abcd', True, 2, 3, 9, 10, 11, {'A': 1, 'B': 2}]
[1, 3, 'abcd', True, 2, 3, 9, 10, 11, {'A': 1, 'B': 2}, 'Adding']
[1, 'in the middle', 3, 'abcd', True, 2, 3, 9, 10, 11, {'A': 1, 'B': 2}, 'Adding']
[1, 'in the middle', 'abcd', True, 2, 3, 9, 10, 11, {'A': 1, 'B': 2}, 'Adding']
3
[1, 'abcd', True, 2, 3, 9, 10, 11, {'A': 1, 'B': 2}, 'Adding']


In [64]:
#sort parmanently
l1=[8,2,10,4]
l1.sort()
print(l1)

l1.sort(reverse=True)
print(l1)

#sort temporarily
print("Temporary sort:", sorted(l1))
print(l1)
l1.reverse()
print("Reverse:", l1)
print("reverse using slicing:", l1[::-1])
#lenght
print("length:",len(l1))
#printing the last element using length
print("The last element:", l1[len(l1)-1])

[2, 4, 8, 10]
[10, 8, 4, 2]
Temporary sort: [2, 4, 8, 10]
[10, 8, 4, 2]
Reverse: [2, 4, 8, 10]
reverse using slicing: [10, 8, 4, 2]
length: 4
The last element: 10


In [16]:
l=[2,6,0,-2,8]
l_=l
l_.append(10)
print(l_)
print(l)
# so l_ is not a new list, just a new reference of the old list
l_=l[:] # new list
l_.append(10)
print(l_)
print(l)

[2, 6, 0, -2, 8, 10]
[2, 6, 0, -2, 8, 10]
[2, 6, 0, -2, 8, 10, 10]
[2, 6, 0, -2, 8, 10]


In [67]:
list1=[1,5,9,3];list2=[5,'B','C','D']
print(list1);print(list2)
list3=list1+list2
print(list3)
print("zip=:",zip(list1,list2))
list4=zip(list1,list2)
print(set(list4))
list_n=['One','Two']
print(set(zip(list1,list2,list_n)))

comb=set(zip(list1,list2,list_n))
#unzipping
x, y, z =  zip(*comb)
print('x =', x)
print('y =', y)

#Existence
print(10 in list1)
print(9 in list1)

[1, 5, 9, 3]
[5, 'B', 'C', 'D']
[1, 5, 9, 3, 5, 'B', 'C', 'D']
zip=: <zip object at 0x000001D87DEA64C8>
{(9, 'C'), (1, 5), (5, 'B'), (3, 'D')}
{(1, 5, 'One'), (5, 'B', 'Two')}
x = (1, 5)
y = (5, 'B')
False
True


In [68]:
# for loop and list
first=[9,4,-5,0,7,5,-10,10,15]
second=[]
for i in first:
    if i>5:
        second.append(i**2)
print(second)

#list comprehension
# [expression for var in collection if condition]
print([i**2 for i in first if i>5])

#HW
# create a list with strings in mixed cases. create a new list with lower case values. code in 3 differet ways
first=['a','abc','ABc']
second=[i.lower() for i in first]
print(second)

[81, 49, 100, 225]
[81, 49, 100, 225]
['a', 'abc', 'abc']


In [18]:
# for loop in lists
l=[1,5,2]
sq_l=[]
for i in l:
    sq_l.append(i**2)
print(sq_l)
print("max:",max(sq_l))
print("sum:",sum(sq_l))

[1, 25, 4]
max: 25
sum: 30


In [19]:
#range star, stop, interval
for i in range(5):
    print(i)
print("Stop")
for i in range(1,4):
    print(i)
print("Stop")
for i in range(1,7,3):
    print(i)

0
1
2
3
4
Stop
1
2
3
Stop
1
4


In [20]:
# Mutable and immutable objects
# Python tuple - immutable
dim=(5,100)
print(dim[0])
print(dim[1])
#dim[1] = 200 # will throw error because tuples are immutable
print(dim)
# print(list(dim)) #will throw error
print(tuple(l))
dim1= 5, 'abc', 7
print(dim1)
dim2=1,2,3,dim1
print(dim2)
a,b,c,d=dim2
print(a);print(b);print(c);print(d)

5
100
(5, 100)
(1, 5, 2)
(5, 'abc', 7)
(1, 2, 3, (5, 'abc', 7))
1
2
3
(5, 'abc', 7)


In [21]:
x1=3;x2=7;
print("x1=",x1,"x2=",x2)
x1,x2=x2,x1 # They are tuples, we have omitted the brackets
print("x1=",x1,"x2=",x2)

x1= 3 x2= 7
x1= 7 x2= 3


In [23]:
listn=[i for i in range(0,20,3)]
print(listn)
for i in listn:
    if i==9:
        continue
    print(i)
    
for i in listn:
    if i==9:
        break
    print(i)

[0, 3, 6, 9, 12, 15, 18]
0
3
6
12
15
18
0
3
6


In [25]:
#while loop
x=250
tot=0
while x>0:
    if tot>1000:
        break
    tot+=x
    print(x,tot)
    #pass 
# pass command is a placeholder which tells about the point from we can start our next lines of code

250 250
250 500
250 750
250 1000
250 1250


In [ ]:
x=[[1,2],[7,8,9],[5,6,9]]

#all the elements
y=[i for j in x for i in j]
print(y)

z=[]
for j in x:
    for i in j:
        z.append(i)
print(z)

# all the elements for the lsit of length atleast 3
z=[]
for i in x:
    if len(i)>2:
        for j in i:
            z.append(j)
print(z)

y=[j for i in x if len(i)>2 for j in i]
print(y)

In [51]:
strings = [['foo', 'bar'], ['baz', 'taz'], ['w', 'koko']]

z=[]
for idx,lst in enumerate(strings):
    for word in lst:
        if len(word)>2:
            for letter in word:
                z.append((letter,idx))
print(z)
print([ (letter.upper(), idx) for idx, lst in enumerate(strings) for word in lst if len(word)>2 for letter in word])

[('f', 0), ('o', 0), ('o', 0), ('b', 0), ('a', 0), ('r', 0), ('b', 1), ('a', 1), ('z', 1), ('t', 1), ('a', 1), ('z', 1), ('k', 2), ('o', 2), ('k', 2), ('o', 2)]
[('F', 0), ('O', 0), ('O', 0), ('B', 0), ('A', 0), ('R', 0), ('B', 1), ('A', 1), ('Z', 1), ('T', 1), ('A', 1), ('Z', 1), ('K', 2), ('O', 2), ('K', 2), ('O', 2)]


# Dictionary

In [73]:
alien = {'color': 'green', 'point': [5,6,7]}
print(alien['point'])
alien['pos']=1
print(alien)
for key, val in alien.items():
    print("key =", key); print("value =",val)
print(alien)
print(alien.items())
for key in alien.keys():
    print("key =", key)
for key in sorted(alien.keys()):
    print("key =", key)
#for val in sorted(alien.values()):
#   print("values =", val) # All the values need to be string or int. There might be alt way to sort

for key,val in sorted(alien.items()):
    print("key =", key,"value =",val)

[5, 6, 7]
{'color': 'green', 'point': [5, 6, 7], 'pos': 1}
key = color
value = green
key = point
value = [5, 6, 7]
key = pos
value = 1
{'color': 'green', 'point': [5, 6, 7], 'pos': 1}
dict_items([('color', 'green'), ('point', [5, 6, 7]), ('pos', 1)])
key = color
key = point
key = pos
key = color
key = point
key = pos
key = color value = green
key = point value = [5, 6, 7]
key = pos value = 1


In [14]:
all_alien=[]
for i in range(5):
    n_alien={'color': 'red', 'point': [7,7,7]}
    all_alien.append(n_alien)
print(all_alien[:2],"\n")
#change some of the element
for alien in all_alien[:3]:
    if alien['color']=='red':
        alien['color']='green'
        alien['point']=[1,1,1]
print(all_alien,'\n')
for no in range(len(all_alien)):
    if all_alien[no]['color']=='green':
        all_alien[no]['color']='red'
        all_alien[no]['point']=[1,1,1]
print(all_alien)

[{'color': 'red', 'point': [7, 7, 7]}, {'color': 'red', 'point': [7, 7, 7]}] 

[{'color': 'green', 'point': [1, 1, 1]}, {'color': 'green', 'point': [1, 1, 1]}, {'color': 'green', 'point': [1, 1, 1]}, {'color': 'red', 'point': [7, 7, 7]}, {'color': 'red', 'point': [7, 7, 7]}] 

[{'color': 'red', 'point': [1, 1, 1]}, {'color': 'red', 'point': [1, 1, 1]}, {'color': 'red', 'point': [1, 1, 1]}, {'color': 'red', 'point': [7, 7, 7]}, {'color': 'red', 'point': [7, 7, 7]}]


# Functions

In [21]:
def sq(x):
    return x*x
print(sq(4))
y=sq(5)
print(y)

def demo_func(x,y,z=1.5):
    if z>1:
        return z*(x+y)
    else:
        return z/(x+y)
print(demo_func(2,5))
print(demo_func(1,1,1))
# default args should be after non-default args
print(demo_func(2,3,1))
print(demo_func(x=2,y=3,z=1))
print(demo_func(2,z=3,y=1))
#print(demo_func(x=2,3,1)) #SyntaxError: positional argument follows keyword argument


16
25
10.5
0.5
0.2
0.2
9


In [30]:
# global variable/namespace , local variable/namespace
b=None
def gl():
    global b
    b=[1,5]
    return b
print(gl())
print(b)

[1, 5]
None


In [32]:
def gl1():
    a=5;b=6;c=7
    return a,b
x=gl1()
y,z=gl1()
print(x,"\n",y,"\n",z)

(5, 6) 
 5 
 6


In [1]:
#Anonymous functions==lambda expression
def sq(x):
    return(x**2)
print(sq(2))
eqvt=lambda x:x**2
print(eqvt(2))
another_one = lambda x,y:x+2*y
print(another_one(2,3))
full = lambda fname, lname: fname.strip().title() +" "+lname.strip().title()
print(full('leonardo  ','da vinci'))

4
4
8


'Leonardo Da Vinci'

In [29]:
authors=['Sarat chatterjee', 'sanjib chattopaddhay', 'rabi thakur', ' narayan sanyal', ' b b banerjee', ' manik bandopaddhay']
help(authors.sort)
authors.sort(key=lambda name: name.split(" ")[-1].title())
print(authors)

words=['abc','hgdj','trg','hdhd']
for word in words:
    print(list(word),'\t', set(list(word)),'\t',len(set(list(word))))
words.sort(key=lambda wrd:len(set(list(wrd))))
print(words)

Help on built-in function sort:

sort(...) method of builtins.list instance
    L.sort(key=None, reverse=False) -> None -- stable sort *IN PLACE*

[' manik bandopaddhay', ' b b banerjee', 'Sarat chatterjee', 'sanjib chattopaddhay', ' narayan sanyal', 'rabi thakur']
['a', 'b', 'c'] 	 {'c', 'a', 'b'} 	 3
['h', 'g', 'd', 'j'] 	 {'j', 'd', 'h', 'g'} 	 4
['t', 'r', 'g'] 	 {'r', 't', 'g'} 	 3
['h', 'd', 'h', 'd'] 	 {'d', 'h'} 	 2
['hdhd', 'abc', 'trg', 'hgdj']


In [14]:
def quad_func(a,b,c):
    return lambda x:a*x*x + b*x +c
q=quad_func(1,1,1)
print(q(0))
print(q(-1))
print(q(1))
#or
print(quad_func(1,1,1)(0))

1
1
3
1


In [18]:
def apply_to_list(some_list,f):
    new_list=[]
    for i in range(len(some_list)):
        new_list.append(f(some_list[i]))
    return new_list
def func1(x):
    return x*x
int=[1,2,3]
print(apply_to_list(int,func1))
print(apply_to_list(int,lambda x:x*x))

[1, 4, 9]
[1, 4, 9]


In [49]:
lst=['name','word','watch']
def f():
    return 'abc'
print(f())
print([f() for x in lst])
print([lambda x:'abc' for x in lst])
print([(lambda x:'abc')(x) for x in lst])

def f(x):
    return 'abc '+x
print(f('k'))
print([f(x) for x in lst])
print([lambda x:'abc '+x for x in lst])
print([(lambda x:'abc '+x)(x) for x in lst])
print(['abc '+x for x in lst],"\n")

print(lambda x:'avc') #returns a function
print((lambda x:'avc')(0)) #returns a value

abc
['abc', 'abc', 'abc']
[<function <listcomp>.<lambda> at 0x0000018D66793EA0>, <function <listcomp>.<lambda> at 0x0000018D6684F598>, <function <listcomp>.<lambda> at 0x0000018D6684FC80>]
['abc', 'abc', 'abc']
abc k
['abc name', 'abc word', 'abc watch']
[<function <listcomp>.<lambda> at 0x0000018D6684FEA0>, <function <listcomp>.<lambda> at 0x0000018D6684F0D0>, <function <listcomp>.<lambda> at 0x0000018D6684FE18>]
['abc name', 'abc word', 'abc watch']
['abc name', 'abc word', 'abc watch'] 

<function <lambda> at 0x0000018D668A8048>
avc


In [51]:
#preventing a funcion from modifying a list
lst=[2,7,9,0]
def func(list1):
    list1[0]=100
    return list1
print(func(lst))
print(lst)

lst=[5,5,5,5]
def func(list1):
    list1[0]=100
    return list1
print(func(lst[:]))
print(lst)

[100, 7, 9, 0]
[100, 7, 9, 0]
[100, 5, 5, 5]
[5, 5, 5, 5]


In [8]:
# passing arbitrary no of arguements in a function
def fo(x):
    print(x)
def fo1(*x):
    print(x)

fo('hero')
fo1('hero','honda')
#print(fo('hero','honda')) # causes error

hero
('hero', 'honda')


In [12]:
temp=[4,5,6,10]
def fo(x):
    for i in x:
        print(i)
def fo1(*x):
    for i in x:
        print(i)

fo(temp)
print("\n")
fo1(temp)
print("\n")
fo1(4,5,6,10)

4
5
6
10


[4, 5, 6, 10]


4
5
6
10


In [25]:
#Map function
#map(function,list)
def sq(x):
    return x*x
z=[1,2,3]
print(map(sq,z))
print(list(map(sq,z)))


[1, 4, 9]


In [45]:
#1 for loop
x=[1,2,3]
y=[]
for i in x:
    y.append(i**2)
print(y)
#2 for loop in function
x=[2,3,4]
def sq(z):
    y=[]
    for i in z:
        y.append(i**2)
    return y
print(sq(x))
#3 list comprehension
x=[3,4,5]
def sq(z):
    y=[i**2 for i in z]
    return y
print(sq(x))
#4 lambda function
x=[4,5,6]
print([(lambda sq:sq**2)(sq) for sq in x])
#5 map function
x=[5,6,7]
def sq(x):
    return x**2
print(list(map(sq,x)))
#6 Map and lambda function
x=[6,7,8]
print(list(map(lambda z:z**2,x)))

[1, 4, 9]
[4, 9, 16]
[9, 16, 25]
[16, 25, 36]
[25, 36, 49]
[36, 49, 64]


In [46]:
# more than one list
l1=[1,2,3]
l2=[3,4,5]
print(list(map(lambda x,y:x*y,l1,l2)))

[3, 8, 15]


In [51]:
#filtering a list
# filter(function name, sequence name)
# function name should return a boolean
z=[-7,1,34,-9,20,22,-90,-13]
print(list(filter(lambda x:x>-10,z)))
print(list(map(lambda x:x>-10,z)))
def func(x):
    if x>0:
        return True
print(list(filter(func,z)))
print(list(map(func,z)))
def func(x):
    if x>0:
        return True
    return False
print(list(map(func,z)))

[-7, 1, 34, -9, 20, 22]
[True, True, True, True, True, True, False, False]
[1, 34, 20, 22]
[None, True, True, None, True, True, None, None]
[False, True, True, False, True, True, False, False]


In [63]:
#reduce a list
#reduce(function name, sequence name)
#applied incrementally by reducing the list
from functools import reduce
l=[1,6,9,12]
print(reduce(lambda x,y:x+y,l))

def max(x,y):
    if x>y:
        return x
    else:
        return y
print(reduce(max,l))
#calculate ci
list=[100,20,20]
print(reduce(lambda x,y:x*(1+y/100),list))

28
12
172.79999999999998


In [5]:
# recursion
def fact(n):
    if n in (0,1):
        return 1
    else:
        return n*fact(n-1)
print(fact(5))


def p(x):
    return print(x)

p(fact(0))
p(fact(1))

def fib(n):
    if n==0:return 0
    elif n==1: return 1
    else: return fib(n-1)+fib(n-2)

p(fib(0))
p(fib(1))
p(fib(2))
p(fib(3))
p(fib(4))

120
1
1
0
1
1
2
3


In [6]:
# faster version
def fib1(n):
    a,b=0,1
    for i in range(n):
        a,b=b,a+b
    return a
p(fib1(0))
p(fib1(1))
p(fib1(2))
p(fib1(3))
p(fib1(4))
#a=0,b=1
#a=1,b=0+1=1
#a=1,b=1+1=2
#a=2,b=1+2=3
#a=3,b=2+3=5

0
1
1
2
3


In [7]:
#import timeit
start = timeit.default_timer()
fib(30)
stop = timeit.default_timer()
print(stop-start)
start = timeit.default_timer()
fib1(30)
stop = timeit.default_timer()
print(stop-start)

1.0858869083810667
0.00014208454670594506


In [8]:
def timestart():
    global start
    start=timeit.default_timer()
    return start
def timestop():
    return print(timeit.default_timer()-start)

timestart()
fib(35)
timestop()

timestart()
fib1(35)
timestop()

11.809767352555284
0.00015360491535432175


In [12]:
def fib2(n):
    fibs = [0, 1]
    for i in range(2, n+1):
        fibs.append(fibs[-1] + fibs[-2])
    return fibs
# Memoization (relatively advanced technique)
def fib3(n, computed = {0: 0, 1: 1}):
    if n not in computed:
        computed[n] = fib3(n-1, computed) + fib3(n-2, computed)
    return computed[n]

# comparsion
timestart()
fib(20)
timestop()

timestart()
fib1(35)
timestop()

timestart()
fib2(35)
timestop()

timestart()
fib3(35)
timestop()
print("\n")
#Checking with last 3
k=2000
timestart()
fib1(k)
timestop()
timestart()
fib2(k)
timestop()
timestart()
fib3(k)
timestop()
print("\n")
#Checking with 2
k=100000
timestart()
fib1(k)
timestop()
timestart()
fib2(k)
timestop()

0.008692118147777705
0.00015040481294192887
0.00015040481295613972
0.00018176581650664048


0.0010240327690524964
0.0019443822202305228
0.0066408525072887414


0.32467022944733515
1.0617946174277648


In [16]:
#sets
l=[1,1,1,2,3,4,4,10]
print(set(l))
k=set(l)
k.discard(1)
print(k)
k.add(1)
print(k)

{1, 2, 3, 4, 10}
{2, 3, 4, 10}
{1, 2, 3, 4, 10}


In [20]:
s1={1,2,3}
s2={2,3,4,5,6}
print(s1|s2)
print(s1.union(s2))
print(s1.intersection(s2))

{1, 2, 3, 4, 5, 6}
{1, 2, 3, 4, 5, 6}
{2, 3}


In [22]:
#keyboard input
x=input("Enter anything here:")
print("Here is the output =",2*x)
print("Here is the output =",2*float(x))

Enter anything here:5.0
Here is the output = 5.05.0
Here is the output = 10.0


In [2]:
#Python libraries
import numpy as np

data1=[1,2,3,6]
print(type(data1))
arr1=np.array(data1)
print("\n",arr1)
print(type(arr1))

data2=[[1,2,3,6],[1,7,84]]
arr2=np.array(data2)
print("\n",arr2)
print(type(arr2),"\t",arr2.ndim,"\t",arr2.shape,'\t',arr2.dtype)

<class 'list'>

 [1 2 3 6]
<class 'numpy.ndarray'>

 [list([1, 2, 3, 6]) list([1, 7, 84])]
<class 'numpy.ndarray'> 	 1 	 (2,) 	 object


In [36]:
data2=[[1,2,3,6],[1,7,84,7]] # balanced row columnb
arr2=np.array(data2)
print("\n",arr2)
print(type(arr2),"\t",arr2.ndim,"\t",arr2.shape,'\t',arr2.dtype)


 [[ 1  2  3  6]
 [ 1  7 84  7]]
<class 'numpy.ndarray'> 	 2 	 (2, 4) 	 int32


In [37]:
data2=[[1,2,3,6],[1,7,84,7.0]] # balanced row columnb
arr2=np.array(data2)
print("\n",arr2)
print(type(arr2),"\t",arr2.ndim,"\t",arr2.shape,'\t',arr2.dtype)
data2=[[1,2,3,6],[1,7,'abc',7.0]] # balanced row columnb
arr2=np.array(data2)
print("\n",arr2)
print(type(arr2),"\t",arr2.ndim,"\t",arr2.shape,'\t',arr2.dtype)


 [[  1.   2.   3.   6.]
 [  1.   7.  84.   7.]]
<class 'numpy.ndarray'> 	 2 	 (2, 4) 	 float64

 [['1' '2' '3' '6']
 ['1' '7' 'abc' '7.0']]
<class 'numpy.ndarray'> 	 2 	 (2, 4) 	 <U11


In [49]:
print(np.zeros(6))
print(np.zeros((2,3)))
print(np.empty((2,3,4)))
print(np.arange(5)) # observe that they are not comma separated
print(np.ones_like(arr2))
arr3=np.array([1,2,4],dtype=np.float64)
print(arr3.dtype)

[ 0.  0.  0.  0.  0.  0.]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[[  2.44001263e-152   1.44507325e+246   2.32530380e+251   2.61697807e+180]
  [  9.74651504e+199   5.27196641e+199   8.72441409e+252   1.12314640e+219]
  [  1.57434286e+161   3.81391467e+180   7.35874515e+223   6.43239166e+246]]

 [[  8.72441596e+252   9.62837851e+199   1.81788002e+185   1.12318896e+219]
  [  1.17008464e+166   8.72441409e+252   1.12314640e+219   1.57434286e+161]
  [  3.81391467e+180   7.35874515e+223   6.43239166e+246   8.79670603e-313]]]
[0 1 2 3 4]
[['1' '1' '1' '1']
 ['1' '1' '1' '1']]
float64


In [52]:
arr=np.array([[1,2,3],[4,5,6]])
# vectorized operatins hence faster than normal for loop
print(arr*arr)
print(arr-arr)
print(arr/2)

[[ 1  4  9]
 [16 25 36]]
[[0 0 0]
 [0 0 0]]
[[ 0.5  1.   1.5]
 [ 2.   2.5  3. ]]


In [5]:
l=np.arange(10)
print(l,'\t',l[0],'\t',l[4:7])
l[2:5]=[10,10,10]
print(l)

l=np.array([[1,2,3],[4,5,6]])
print(l,'\n',l[1],'\n',l[1][2],'\t',l[1,2])

[0 1 2 3 4 5 6 7 8 9] 	 0 	 [4 5 6]
[ 0  1 10 10 10  5  6  7  8  9]
[[1 2 3]
 [4 5 6]] 
 [4 5 6] 
 6 	 6


In [19]:
np.random.seed(10)
names=np.array(['bob','david','dickson','robert','joe'])
print(names=='bob')
data=np.random.randn(5,3)
print(data)
print('davids -',data[names=='david'])
print('davids -',data[names=='david',1:])
print('data<0',data[data<0])

[ True False False False False]
[[ 1.3315865   0.71527897 -1.54540029]
 [-0.00838385  0.62133597 -0.72008556]
 [ 0.26551159  0.10854853  0.00429143]
 [-0.17460021  0.43302619  1.20303737]
 [-0.96506567  1.02827408  0.22863013]]
davids - [[-0.00838385  0.62133597 -0.72008556]]
davids - [[ 0.62133597 -0.72008556]]
data<0 [-1.54540029 -0.00838385 -0.72008556 -0.17460021 -0.96506567]


In [33]:
arr=np.empty((5,4))
print(arr)
for i in range(5):
    arr[i]=int(i)
print(arr)
print(arr[[1,3]])
print(arr.T)
print(np.dot(arr,arr.T))

[[ 0.  1.  2.  3.]
 [ 4.  0.  1.  2.]
 [ 3.  4.  0.  1.]
 [ 2.  3.  4.  0.]
 [ 1.  2.  3.  4.]]
[[ 0.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 2.  2.  2.  2.]
 [ 3.  3.  3.  3.]
 [ 4.  4.  4.  4.]]
[[ 1.  1.  1.  1.]
 [ 3.  3.  3.  3.]]
[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]
[[  0.   0.   0.   0.   0.]
 [  0.   4.   8.  12.  16.]
 [  0.   8.  16.  24.  32.]
 [  0.  12.  24.  36.  48.]
 [  0.  16.  32.  48.  64.]]


In [35]:
vect1=np.array([2,3,4,5])
vect2=np.array([1,1,1,1])
print(np.dot(vect1,vect2))

14
